name: Build LKM (Debug)

on:
  push:
    branches: [ "main", "master" ]
    paths:
      - 'code/**'
      - '.github/workflows/build-lkm.yml'
  pull_request:
    branches: [ "main", "master" ]
    paths:
      - 'code/**'
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/ddk-lkm.yml
    with:
      kmi: 'android14-6.1'
      ddk_release: '20260313'
      source_dir: 'code'
